version: '3.8'

services:
  app:
    container_name: jugsie_app
    build:
      context: app
      dockerfile: dev.dockerfile
    restart: always
    networks:
      - jugsie_network
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    env_file: app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: jugsie_db
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jugsie
      - POSTGRES_PASSWORD=jugsie
      - POSTGRES_DB=jugsie_dev
    networks:
      - jugsie_network

volumes:
  postgres_data:

networks:
  jugsie_network:
    driver: bridge
