version: '3.8'

services:
  app:
    container_name: jugsie_app
    build:
      context: app
      dockerfile: dev.dockerfile
    restart: always
    networks:
      - jugsie_network
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    env_file: app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: jugsie_db
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - jugsie_network
    ports:
      - "5432:5432"

networks:
  jugsie_network:
    driver: bridge
