services:
  app:
    container_name: jugsie_app
    build:
      context: app
      dockerfile: prod.dockerfile
    env_file:
      - app/.env
    restart: always
    networks:
      - jugsie_network
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
